version: '3'
services:
  virtual-ccf:
    image: $REGISTRY/ccf/virtual:${TAG:-latest}
    network_mode: "host"
    depends_on:
      - keygenerator
    volumes:
      - ./certs:/app/certs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CCF_PLATFORM=virtual
        - CCF_VERSION=5.0.0-dev10
  snp-ccf:
    image: $REGISTRY/ccf/snp:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CCF_PLATFORM=snp
        - CCF_VERSION=5.0.0-dev10
  keygenerator:
    image: mcr.microsoft.com/ccf/app/dev:5.0.0-dev10-virtual
    volumes:
      - ./certs:/certs
    command: /bin/bash -c "cd /certs && /opt/ccf_virtual/bin/keygenerator.sh --name member0 --gen-enc-key"
